export const trendingWebsites = [
  { name: "Google", url: "https://www.google.com" },
  { name: "YouTube", url: "https://www.youtube.com" },
  { name: "Instagram", url: "https://www.instagram.com" },
  { name: "WhatsApp", url: "https://www.whatsapp.com" },
  { name: "ChatGPT", url: "https://chatgpt.com" },
  { name: "Amazon India", url: "https://www.amazon.in" },
  { name: "Cricbuzz", url: "https://www.cricbuzz.com" },
  { name: "Bing", url: "https://www.bing.com" },
  { name: "Wikipedia", url: "https://www.wikipedia.org" },
  { name: "X (Twitter)", url: "https://www.x.com" },
  { name: "Google India", url: "https://www.google.co.in" },
  { name: "Times of India", url: "https://timesofindia.indiatimes.com" },
  { name: "Reddit", url: "https://www.reddit.com" },
  { name: "Flipkart", url: "https://www.flipkart.com" },
  { name: "Hotstar", url: "https://www.hotstar.com" },
  { name: "Quora", url: "https://www.quora.com" },
  { name: "LinkedIn", url: "https://www.linkedin.com" },
  { name: "OpenAI", url: "https://www.openai.com" },
  { name: "MSN", url: "https://www.msn.com" },
  { name: "Netflix", url: "https://www.netflix.com" },
  { name: "IndiaTimes", url: "https://www.indiatimes.com" },
  { name: "Samsung", url: "https://www.samsung.com" },
  { name: "Adobe", url: "https://www.adobe.com" },
  { name: "Indian Railways", url: "https://www.indianrail.gov.in" },
  { name: "SBI", url: "https://www.sbi.co.in" },
  { name: "Paytm", url: "https://www.paytm.com" },
  { name: "IRCTC", url: "https://www.irctc.co.in" },
  { name: "HDFC Bank", url: "https://www.hdfcbank.com" },
  { name: "NDTV", url: "https://www.ndtv.com" },
  { name: "Pinterest", url: "https://www.pinterest.com" },
  { name: "Indian Express", url: "https://www.indianexpress.com" },
  { name: "Justdial", url: "https://www.justdial.com" },
  { name: "Telegram", url: "https://t.me" },
  { name: "Live Hindustan", url: "https://www.livehindustan.com" },
  { name: "Hindustan Times", url: "https://www.hindustantimes.com" },
  { name: "Toppr", url: "https://www.toppr.com" },
  { name: "OneIndia", url: "https://www.oneindia.com" },
  { name: "Jagran", url: "https://www.jagran.com" },
  { name: "Myntra", url: "https://www.myntra.com" },
  { name: "Business Standard", url: "https://www.business-standard.com" },
  { name: "Moneycontrol", url: "https://www.moneycontrol.com" },
  { name: "Zee News", url: "https://zeenews.india.com" },
  { name: "Economic Times", url: "https://economictimes.indiatimes.com" },
  { name: "Firstpost", url: "https://www.firstpost.com" },
  { name: "News18", url: "https://www.news18.com" },
  { name: "LiveMint", url: "https://www.livemint.com" },
  { name: "India Today", url: "https://www.indiatoday.in" },
  { name: "Naukri", url: "https://www.naukri.com" },
  { name: "Flipkart Stories", url: "https://stories.flipkart.com" },
  { name: "BookMyShow", url: "https://www.bookmyshow.com" },
];
